### ISSUE TITLE
Endpoints missing from documentation

### ISSUE THREAD

**Issue by caseychoiniere** [Duke-Translational-Bioinformatics/duke-data-service#1040]
I noticed that `GET /api/v1/folders/{id}/children` and `GET /api/v1/projects/{id}/children` seem to be missing from the official docs at https://api.dataservice.duke.edu/apidocs/

**Comment by dmann** [comment]
Is this what you're looking for?

https://api.dataservice.duke.edu/apidocs/folders_files.html#search-children

**Comment by caseychoiniere** [comment]
No. There's GET/children endpoints for projects and folders. You'll see them if you go to API explorer.

**Comment by caseychoiniere** [comment]
They return a list of all children for the folder/project with ID as the only param

**Comment by caseychoiniere** [comment]
They return a list of all children for the folder/project with ID as the only param

**Comment by caseychoiniere** [comment]
@dmann You're right. I think we use to have `search/children` listed separately from `get/folders/{id}/children` Sorry about the noise
