### ISSUE TITLE
file tags: UI/UX

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service#108]
design UI/UX elements; similar to annotations

**Comment by jonturneratduke** [comment]
?? Need to define this a bit (lot?) more. Erich?

**Comment by caseychoiniere** [comment]
Needs description/explanation of deliverable.

**Comment by erichhuang** [comment]
We'd like researchers to be able to do two things. 
* annotate data with key value pairs
* tag data 

We imagine this will enrich researchers ability to add informative metadata that is more arbitrary than formal provenance. We ultimately would like to engineer it so the UI will autocomplete these metadata (as in Evernote)

**Comment by jonturneratduke** [comment]
Not MVP.
