### ISSUE TITLE
Feature request: Look up users by email/username

### ISSUE THREAD

**Issue by dleehr** [Duke-Translational-Bioinformatics/duke-data-service#1103]
In [DukeDSClient](https://github.com/Duke-GCB/DukeDSClient), we've implemented commands to share/deliver projects to other DukeDS users from the command-line. The API calls ([e.g. project permissions](https://api.dataservice.duke.edu/apidocs/projects.html#project-member-permissions-project-permission-instance-put)) require the user's DDS UUID, which is not something we'd encourage users to try to type on the command-line. So for this use case, we resolve the UUIDs from a username or email address. These are user-friendly, reliable, and easy to discover.

In order to resolve usernames/emails to UUIDs, we fetch the entire list of users from [GET /users](https://api.dataservice.duke.edu/apidocs/users_software_agents.html#users-users-collection-get), paging through 25 at a time. The user records contain username and email, so we can filter against our user parameters.

The current user list seems to be around 300, so at 25 per page, we'd be making at least 12 requests to fetch the entire user list. In contrast, when we share/deliver a project we currently only support one recipient. While we're expanding that to allow multiple, it would likely be 2-3 at a time.

https://github.com/Duke-GCB/DukeDSClient/blob/f4c192dfd6657a8d6f85ccb3050d4c9c936bfa25/ddsc/core/remotestore.py#L194

https://github.com/Duke-GCB/DukeDSClient/blob/f4c192dfd6657a8d6f85ccb3050d4c9c936bfa25/ddsc/core/remotestore.py#L115

https://github.com/Duke-GCB/DukeDSClient/blob/f4c192dfd6657a8d6f85ccb3050d4c9c936bfa25/ddsc/core/remotestore.py#L173

Other notes:

1. We can (and do) use the [POST /auth_providers/:id/affiliates/:uid/dds_user](https://api.dataservice.duke.edu/apidocs/users_software_agents.html#auth-provider-affiliates-create-user-account-for-affiliate-post) API when we have a username, but I'd assume most of the lookups are done by email address.
2. [GET /users](https://api.dataservice.duke.edu/apidocs/users_software_agents.html#users-users-collection-get) does support searching by parts of a name, but we'd prefer a simple, strict lookup by username or email (exact matches, no "contains")

So currently, every time we look up a user, we fetch the entire list of users from the API (currently ~300 with 25 per page), then filter it client-side for matches on names/emails

**Comment by dleehr** [comment]
It would be great to include these query parameters (mail, NetID) as well as sorting on the affiliate user search endpoint too. We're proxying other DukeDS APIs like projects (#1227) to be able to sort/filter, but can't do that until the entire list is fetched.

**Comment by dleehr** [comment]
This can be closed, thanks!

**Comment by dmlond** [comment]
great!
