### ISSUE TITLE
authentication: contact duke Box team

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service#115]
Darin L. to contact duke Box implementation team - learn how they integrated duke user directory (IDMS data? LDAP? other??)

**Comment by dmlond** [comment]
According to Shilen Patel, Box.duke has a rest API that they use to run a daily update of new Duke Users.  This is why you cannot find people in their system one day, but may find them the next day.  It is also why the provide the ability to create an invite link to send to someone via email or chat, etc.

**Comment by dmlond** [comment]
According to Shilen Patel, Box.duke has a rest API that they use to run a daily update of new Duke Users.  This is why you cannot find people in their system one day, but may find them the next day.  It is also why the provide the ability to create an invite link to send to someone via email or chat, etc.
