### ISSUE TITLE
Production - User exists twice in "GET/users?name_contains"

### ISSUE THREAD

**Issue by caseychoiniere** [Duke-Translational-Bioinformatics/duke-data-service#1191]
When I do a search for a specific user to add them to a project `GET/api.dataservice.duke.edu/api/v1/users?full_name_contains=` returns two results. They're identical with the exception of the DDS UUID. This makes it impossible to add them to a project. 

This is only in production. Dev and test are fine.

User is Sara Calvert.

This is a bit of a time sensitive issue as I'm trying to get this user set up in DDS for another project.

**Comment by dmlond** [comment]
This should work now.

**Comment by caseychoiniere** [comment]
It's fixed. Thanks!
