### ISSUE TITLE
microphone

### ISSUE THREAD

**Issue by dmlond** [Duke-Translational-Bioinformatics/duke-data-service#120]

**Comment by jonturneratduke** [comment]
get a proper condenser microphone (& webcam?) to make meeting with Casey easier.

**Comment by jonturneratduke** [comment]
Will use department "snowball" mic to gauge performance... if that doesn't work, Wirecutter.com review (& soundcloud recording) show Blue Yeti to be the best bang/buck @ around $129 . http://thewirecutter.com/reviews/the-best-usb-microphone/  

http://www.bhphotovideo.com/c/search?Ntt=blue+yeti
