### ISSUE TITLE
Lookup DukeDS Users from NetID

### ISSUE THREAD

**Issue by dleehr** [Duke-Translational-Bioinformatics/duke-data-service#1235]
We're making some improvements to our Data Delivery application at https://datadelivery.genome.duke.edu as noted in https://github.com/Duke-GCB/D4S2/issues/107. In short, we'd like to look up a Duke DS user from a Duke NetID

For users who do not yet have a DukeDS user record, this is pretty straightforward. [POST auth\_providers/:id/affiliates/:uid/dds\_user](
https://api.dataservice.duke.edu/apiexplorer#!/auth_providers/postApiV1AuthProvidersIdAffiliatesUidDdsUser) creates the user record and returns it in the response.

However, if the user object already exists, that endpoint returns a boilerplate 409 response. We have no way to directly query what the User's DukeDS ID is - we'd have to query the users endpoint and locally match based on NetID (See 
https://github.com/Duke-Translational-Bioinformatics/duke-data-service/issues/1103)

One option would be to simply include the user ID (or full user record) in that 409 response. But I wouldn't complain about a more comprehensive NetID -> DukeDS User endpoint 😄

**Comment by dmann** [comment]
@dleehr issue #1103 you ask for both `username` and `email` as  filter options for the `/users` endpoint. For the record, we enforce uniqueness on `username`, but not on `email`. Are you still interested in an `email` filter, even if it possibly returns multiple users?

**Comment by dleehr** [comment]
Yes, we're interested in the email filter.

**Comment by dmann** [comment]
@dleehr `username` and `email` filters for the `/users` endpoint have been deployed to our develop instance. Try it out and let me know what you think:

API Docs:
https://apidev.dataservice.duke.edu/apidocs/users_software_agents.html#users-users-collection

API Explorer:
https://apidev.dataservice.duke.edu/apiexplorer#!/users/getApiV1Users

**Comment by dleehr** [comment]
Looks great on dev, thanks! Will these filters be added to [Auth Provider Affiliates GET](https://apidev.dataservice.duke.edu/apidocs/users_software_agents.html#auth-provider-affiliates-list-auth-provider-affiliates-get) too?

**Comment by dmann** [comment]
Sure, the List Auth Provider Affiliates could have `username` and `email` filters added. It's not as straight forward as the `/users` endpoint, so it'll probably take me longer to get that feature out.

Since the `/users` update looks good to you, I think it can be part of this week's deployment to Production (10-10). Given my current workload, the Affiliates update will probably be ready next week sometime and possibly deployed to prod 10-24. How does that sound to you?

**Comment by dleehr** [comment]
Sounds good, thanks @dmann

**Comment by dmann** [comment]
@dleehr We've deployed `username` and `email` filters for Auth Provider Affiliates to uatest. When you get a chance, can you test it out and let us know if it's working as you expect? Thanks!

**Comment by dleehr** [comment]
Thanks @dmann! We're looking at it now

**Comment by dleehr** [comment]
I think so. I'm actually working on our application that will consume this endpoint today, so I'll do my best to give a yea or nay today.

**Comment by dleehr** [comment]
@dmann Looks good, thanks!

**Comment by dleehr** [comment]
Feel free to close this. Thanks again!
