### ISSUE TITLE
member management: UI

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service#129]
(replaces #82)
build UI components of member management feature.
assignment of users to a project.
    add
    remove

for MVP, all users are admin

**Comment by caseychoiniere** [comment]
Are you looking for the deisign here or functional components?

**Comment by erichhuang** [comment]
Yeah. Obviously once the services are deployed, actual UI components. But this sounds like a later sprint. Jon? UI/UX **design**?

**Comment by caseychoiniere** [comment]
That makes sense. UI in Sprint 2 is still in design phase. Thanks, I can close this issue.

**Comment by jonturneratduke** [comment]
Actually, I thought this was a Darrin/Darin task, to build a basic (placeholder?) UI that would exercise the API and provide basic functionality. There are also tests which go along with this item.
