### ISSUE TITLE
member management: API

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service#131]
(replaces #82)
build API components of member management feature.
assignment of users to a project.
    add
    remove

for MVP, all users are admin

**Comment by dmann** [comment]
I'm making the assumption that this is actually for the Project Affiliates endpoints described here:
http://docs.dukedataservices.apiary.io/#projectaffiliates

**Comment by dmann** [comment]
- [ } Stub out endpoints
- [ } Return serialized objects
- [ } Authenticate!
- [ } Return validation errors

**Comment by dmann** [comment]
- [ ] Stub out endpoints
- [ ] Return serialized objects
- [ ] Authenticate!
- [ ] Return validation errors
