### ISSUE TITLE
Trouble sharing data with guest Duke account

### ISSUE THREAD

**Issue by suchang112** [Duke-Translational-Bioinformatics/duke-data-service#1381]
I am having trouble sharing my sequencing data on Duke Data Service with a guest Duke account. The guest Duke account has been set up and the user was able to log in. The guest could see sequencing data that was shared by another lab a while back, but not me. Every time I tried to share the data, I received an error message "405 Method not allowed." Can anyone please help me with this? Thank you!

**Comment by dmlond** [comment]
Please open a [ServiceNow Ticket](https://duke.service-now.com) and target Systems-Unix-OIT. Add your NetID, the DDS Project ID, and the NetID of the Guest User in the Ticket.
