### ISSUE TITLE
API endpoint: project folder

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service#156]
create endpoints and tests

**Comment by jonturneratduke** [comment]
create, delete, move, get children, parents, etc. see apiary.io

**Comment by dmann** [comment]
- [ ] Folder model + migration + associations
- [ ] Folder + Project model specs
- [ ] Folder endpoints
- [ ] Folder endpoint specs
- [ ] Architect api
