### ISSUE TITLE
Explore swift clients w.OIT OpenStack service

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service#193]
Yesterday and Today I have been playing with the various python and ruby swift clients with the OIT OpenStack service.

**Comment by dmlond** [comment]
-[x] I have been able to generate and use temporary-urls to get an object from swift
-[x] I have been able to generate a temporary-url to POST a file using the form-post-middleware
-[] I have been able to generate a tempoary-url to PUT an update to an object
-[] I have been able to generate a temporary-url to PUT a static-large-object manifest

**Comment by dmlond** [comment]
I have posted a question to ask.openstack.org to find out how to use temporary-urls to store static-large-objects

**Comment by dmlond** [comment]
I am able to create dynamic large objects using temporary PUT urls.  This would get us moving forward, but some online questions state that dynamic large object downloads might be slower than static large object downloads

**Comment by dmlond** [comment]
just to play, I was able to create a static-large-object authenticated as myself, and then generate a temporary signed GET url to download it, and that works.  So, the missing part of the puzzle is the ability to generate a temporary signed PUT url to upload a manifest
