### ISSUE TITLE
data subsets

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service#20]
AAU, I want to be able to create and organize subsets of data (groupings of data, workflows) within a project

**Comment by erichhuang** [comment]
Can a folder accomplish this aim?

**Comment by jonturneratduke** [comment]
Yes, IMO that's a perfectly reasonable implementation and probably the most familiar idiom for users. (Other ways could include filtering views, searches based on keywords/dates/datatypes, etc.) Of course, as the Voice Of The Customer, it's your call. :) During the end-of-sprint demo, you review the implementation and decide if it meets your needs; accept it or reject it.

**Comment by erichhuang** [comment]
Yes. I see two ways:
1. Folders
2. Tags/Annotations
