### ISSUE TITLE
followup on server storage. 1TB local storage

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service#202]
28GB assigned instead of 1TB requested.

Sal asked for connection settings to Isilon, waiting for response.

**Comment by jonturneratduke** [comment]
only critical path for PHI data, not for development

**Comment by jonturneratduke** [comment]
jon- follow up with Sal. Status??

**Comment by jonturneratduke** [comment]
followed up email Sal Monday (he was OOO).

**Comment by jonturneratduke** [comment]
isilon shares mounted @10.12.56.30, 10.12.56.28, 10.12.56.29, 10.12.56.27
The export path is duhsnas-pri:/ifs/Application File Shares/DUSOM/FRDS-Test_fs

Brandon Tzortzis & david hetrick worked on this yesterday & today and confirmed with Matt.

**Comment by erichhuang** [comment]
Awesome
