### ISSUE TITLE
deploy auth service on DHTS servers

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service#204]
Probably Capistrano, but possibly Ansible? uncertain.

**Comment by dmlond** [comment]
DHTS will need to open our servers up to the world.

**Comment by dmlond** [comment]
the server iptables firewall is provisioned properly to handle 80 and 443 calls.  DHTS needs to create a proxy which will be open to the world at hostnames that Matt G. specified.

**Comment by dmlond** [comment]
the server iptables firewall is provisioned properly to handle 80 and 443 calls.  DHTS needs to create a proxy which will be open to the world at hostnames that Matt G. specified.

**Comment by dmlond** [comment]
I am going to close this card.  The code is deployed and running properly on the server, we are now dependent on DHTS to create the proxy.
