### ISSUE TITLE
Make MVP Specific Wireframe

### ISSUE THREAD

**Issue by dmlond** [Duke-Translational-Bioinformatics/duke-data-service#232]

**Comment by jonturneratduke** [comment]
API team is a separate effort from UI team. Assignments should be Coordinated through myself and Donald. Happy to discuss in detail if needed.

**Comment by pbmorrison** [comment]
We need to see the link between UI components to endpoints, if possible.  Possibly in a comment?

**Comment by jonturneratduke** [comment]
API endpoitns should be distinct and not dependent upon UI implementation. Separate task. We can pretend consumer is a python script (and it shall be, some day) — that should have no effect upon API implementation.

**Comment by jonturneratduke** [comment]
One further point that needs to be made -- assignments to Casey, Ben, etc. should happen after a discussion and agreement with me. RAD development is a separate workstream. We agreed last week that Donald and I would own the waffle board and handle respective team assignments. I don't want to introduce confusion into Casey's tasks nor distraction.

**Comment by dmlond** [comment]
For now, the UI implementation is the primary driver of the endpoints necessary. There may be a better way to coordinate this, but it needs to be coordinated.  We need to see a list of all the endpoints that the UI needs to do its work, with links to Apiary, and Specs detailed in Apiary.  Otherwise, it is highly likely that something will get missed.

**Comment by caseychoiniere** [comment]
Not really sure what this is pertaining to. Wireframes for the MVP were completed and posted to the Slack UI/UX channel. If something needs to be changed with the existing set of MVP wireframes, then please create a more detailed issue highlighting the specific changes desired. I went ahead and reposted a link to the wireframes and added a PDF.
