### ISSUE TITLE
Identify Endpoints required by MVP Wireframe

### ISSUE THREAD

**Issue by dmlond** [Duke-Translational-Bioinformatics/duke-data-service#233]
use links to apiary in wireframe comments

**Comment by caseychoiniere** [comment]
Comments have been added with links to Apiary for each page/component. Here is a link or you can also access these comments by viewing the wireframes that are linked on the Slack UI/UX channel. https://live.uxpin.com/ee59d60bf0ca8eafac0bb2808632d20e03a0b8c9#/pages/24776593/sitemap/add-comment
