### ISSUE TITLE
tech stack: Heroku

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service#25]
Heroku (deployment)
			-Create account (Pcard)

**Comment by jonturneratduke** [comment]
-each project member create own (free) account.
-create corporate/project account (pcard).
-set up dev stack
-set up test stack

**Comment by jonturneratduke** [comment]
Dependent upon DHTS servers

**Comment by jonturneratduke** [comment]
============================
Summary:
with metadata encryption in database: $334/month
no metadata encryption in database: $184/month
============================
TWO 1x machines for production
ONE Hobby Tier machine for staging
free tier machines for developers
with the following add-ons:
    New Relic: "wayne" level 
    Papertrail 
    Heroku Scheduler
    SSL->Heroku
============================




1x machine can run 3 servers (3 concurrent requests)
Hobby tier is a 1x machine, but we can run only 1 at a time (no fallover)

PRODUCTION: 
   TWO 1x dynos to start (2@ $50)

STAGING
   can be Free or Hobby Tier (1@ $7)

DEVELOPER
   Developers can run Free tier (6 hour sleep in 24 hour period is okay), or local
 
database:
   If encryption of metadata is needed by ISO, we need PREMIUM POSTGRES @ $200/month
   if encryption is NOT required, we can use standard db @ $50/month


add-ons:
   $0.00  New Relic: "wayne" level  (free, provides enough info and backup)
   $20/mo     SSL->Heroku addon (allows us to use our own host as an endpoint)
   $7/mo        Papertrail logging tool. Can drain elsewhere for archival. 1 week search, one year storage, 50MB/day accumulation.
   $0.00   Heroku Scheduler - like cron. lets us fire off tasks based on time.

**Comment by jonturneratduke** [comment]
waiting for response from Rosemary Herhold w/r/t/ requirement to encrypt database.

**Comment by erichhuang** [comment]
I say we go ahead and encrypt at rest

**Comment by jonturneratduke** [comment]
two hobby servers + hobby postgres dbs are allocated now.
The dynos are :
   https://warm-journey-5070.herokuapp.com/
   https://ancient-fortress-7578.herokuapp.com/ 

I have a meeting Thursday with Rosemary to work through a Schedule A form for Heroku.

**Comment by jonturneratduke** [comment]
dependent on ISO approval of contract language

**Comment by jonturneratduke** [comment]
see task #207 - iso has approved. waiting for signature from Heroku Security Officer
