### ISSUE TITLE
tech stack: CircleCI

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service#26]
CircleCI (continuous integration)
			-Create account
			-strategy: how to integrate to github
				-create dev & test branches
				-integrate with main branch

**Comment by JamesM967** [comment]
I sent out invites for the CircleCI integrated project. Circle is already generating a build every time someone pushes to master. It will also generate a build if you create a pull request to master.

**Comment by erichhuang** [comment]
Thanks James.

E
