### ISSUE TITLE
tech stack: user authentication

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service#32]
integration with Shibboleth. what are the issues? (e.g. are we going to wrap authentication providers with our own token? OAUTH, Shibboleth). When do we add users - at point of first authentication? What about adding users “on behalf of”?  investigate Heroku “One Login” single sign on.

**Comment by jonturneratduke** [comment]
Register application for use with Shibboleth.
each server has its own registry entry.

related to deploying Heroku /  workcycle.

**Comment by dmlond** [comment]
I have hit a roadblock using shibboleth in heroku.  The custom buildpack uses an older version of shibboleth and apache designed to work on cedar-10 which will not be available after Nov this year.  The developer status that he is interested in creating a new one to work with cedar-14, but there is not guarantee.  I also ran into some technical issues involving the differences in the way this shibboleth works, and the way the shibboleth that we use here works.

**Comment by dmlond** [comment]
I think there was talk of using a separate Authentication frontend that is duke hosted (or hosted on another platform) which would allow users of the main site to choose a duke login, be routed to the duke system, which handles shibboleth, and returns them to the main site with a Jason Web Token in the url parameters or cookies.
