### ISSUE TITLE
Dev is returning "ua_test" in portal config environment

### ISSUE THREAD

**Issue by caseychoiniere** [Duke-Translational-Bioinformatics/duke-data-service#345]
Shows ua_test footer instead of dev footer

**Comment by caseychoiniere** [comment]
Again, this isn't a portal issue. This is an issue with DDS. Darin is aware of it and I opened an issue there about a month ago. Maybe we should get rid of the colored footers if they aren't going to fix it. This issue has been posted and removed from Portal 3 times now.

**Comment by caseychoiniere** [comment]
@mgardnerpsu This is a DDS problem not a portal issue. Please see comments above. @dmlond has more info on this.

**Comment by dmlond** [comment]
running Ruby on Rails in development mode uses more memory than running in uatest or production, and eventually causes the heroku instance to use up its memory and restart. This has to do with default behaviors of Ruby on Rails that we have not be able to configure to act differently when running in development mode.
