### ISSUE TITLE
Can't delete project

### ISSUE THREAD

**Issue by caseychoiniere** [Duke-Translational-Bioinformatics/duke-data-service#349]
I can delete most projects but cannot delete project id#2f30fdeb-ba8d-42fa-a1f1-57d9fb8bcd57 in dev.
There are no other members of the project and I am the admin. The DELETE request goes through fine and returns the proper 204 code but the project is not deleted. Not sure if this is an isolated bug because I seem to have no problem deleting other projects. This project does have a lot of files in it.

**Comment by dmann** [comment]
Commit 01b2b97d4ef868fad45503bb887951094b0646a0 should fix this issue.

**Comment by caseychoiniere** [comment]
This is fixed now. Thanks dMann!
