### ISSUE TITLE
project dashboard

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service#35]
write some code to pull metrics from github/Waffle.io - tasks (velocity, burndown, outstanding, projected ship date, etc.) Show as a dashboard for project leadership & management

**Comment by erichhuang** [comment]
Useful reference: https://developer.github.com/v3/issues/

**Comment by benneely** [comment]
2jun - breaking this task down into subtasks for estimating sprint 0, sprint 1

**Comment by benneely** [comment]
created 8 subtasks
