### ISSUE TITLE
dataservice.duke.edu redirect missing a slash

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service#357]
http://dataservice.duke.edu/ is redirecting to "https://dataservice.duke.edu/portal#/home" which fails, and enters a redirection loop, cycling between:  https://dataservice.duke.edu/portal#/home    and     https://dataservice.duke.edu/portal#/login

It looks like we're missing a slash betw. "portal" and "#"

**Comment by caseychoiniere** [comment]
Check cookies in your resource tab. I had this happen this morning and it was an apiToken cookie that hadn't been cleared out by the logout method for some reason. Currently the app clears the api token on logout or if you get a 403 error. But I suspect I need to set an expiration on it that matches the actual api token expiration.

**Comment by caseychoiniere** [comment]
In fact, I just confirmed that this is the issue. Surprised it hadn't showed up earlier. I will open an issue in portal and get it figured out asap.

**Comment by jonturneratduke** [comment]
Good catch. I thought maybe it was the root redirect in rails... so many moving parts!
Sorry API team!!!
