### ISSUE TITLE
Sprint 1 planning & estimates

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service#36]
Point out backlog items
select items for sprint 1

**Comment by jonturneratduke** [comment]
We need to make a pass through the backlog, estimating complexity for the user stories & MVP features.

We will work off the sprint plan (http://publish.smartsheet.com/0ad7469604c94e3db014237f8f94e897) as a rough guide, so getting a good feel for the first 2 sprints will be essential, and recognizing it’s harder and unreliable to look far into the future. We will also want to give thought to technical debt along the way (items such as DHTS Isolon workstreams) which may not be accounted for in the user stories. Let’s see how far along we can get, and we can schedule additional time if necessary.

**Comment by jonturneratduke** [comment]
done. ~1250 hours for MVP.

**Comment by erichhuang** [comment]
So around 16 weeks?

**Comment by jonturneratduke** [comment]
It still needs some fine tuning, but estimate at this moment is 6 sprints, or 18 weeks.

Most of the 1250 time is critical path where developer capacity is the limiting factor. Our core developer capacity is around 200/sprint. (~66/week). Ben’s work can run in a parallel stream alongside D/D/J’s* work.

*Darin, Darrin, James
