### ISSUE TITLE
Allow projects to be created with same name

### ISSUE THREAD

**Issue by erichhuang** [Duke-Translational-Bioinformatics/duke-data-service#364]
I totally see many situations where a User will end up creating a Project that has the same name as an old deleted Project and tearing their hear out because of the error thrown.

Can we revise the API such that if `is_deleted == TRUE`, a User can create a new Project with the same name?

**Comment by dmann** [comment]
We're currently only validating against projects where is_deleted=false. Maybe you found an edge case? What is the project name that you were trying to create? Also, were you in dev, uatest, or prod?

**Comment by erichhuang** [comment]
Since multiple people have reported this bug today, even if we're enforcing uniqueness for `is_deleted = false`, would it be true if that an error would be thrown if User 1 creates a Project `My Favorite Project` and then User 2 tries to create an identically named Project? I'm in favor of throwing out a uniqueness constraint and relying on UUIDs to distinguish identically named Projects.

**Comment by caseychoiniere** [comment]
Seems that this isn't a problem on dev anymore. I can create and delete `Test Project` and then create a new project called `Test Project` no problem. On production this still fails though.

**Comment by erichhuang** [comment]
Hey @caseychoiniere, can you try to create a Project named `My Project` on production?

**Comment by caseychoiniere** [comment]
Yeah, it failed.

**Comment by caseychoiniere** [comment]
So uniqueness constraints are across the system?

**Comment by erichhuang** [comment]
Looks like it. I think that's too rigid. That's why we have UUIDs.

**Comment by mgardnerpsu** [comment]
We decided as a team that projects with the same name should be allowed.
