### ISSUE TITLE
test stack: Heroku stacks

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service#37]
-each project member create own (free) account.
-set up dev stack
-set up test stack

**Comment by jonturneratduke** [comment]
dependent on conversation with Dave.

**Comment by dmlond** [comment]
I created a dev account, a couple of projects, and deployed to the project.

**Comment by jonturneratduke** [comment]
is this something we can close out by 6/19?

**Comment by jonturneratduke** [comment]
Dependent upon DHTS servers
