### ISSUE TITLE
tech stack: CircleCI for Dev Environment

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service#38]
Configure CircleCI to automatically deploy the develop branch of the GitHub DDS repository to the Develop Heroku Stack when the tests pass

**Comment by jonturneratduke** [comment]
note: may want David B.'s input on structure: master, dev, production?

**Comment by jonturneratduke** [comment]
Dependency on #39

**Comment by dmlond** [comment]
we wrote a [contributing](https://github.com/Duke-Translational-Bioinformatics/duke-data-service#contributing) section detailing the (initial) steps developers should take to work their code changes into production.  Currently, we all work on the 'develop' branch (push,pull) directly in the duke data services repo.  We should set up a CircleCI test for this as soon as we have the basic rails scaffold.  It should also automatically deploy to a develop heroku project in the team heroku account if CircleCI rspec tests pass.  As soon as we move to ua_test, we will create a 'ua_test' branch on github, merge from develop, and CircleCI should be wired to test it and move it to a ua_test team heroku project.  Finally, we move to production the same way.

**Comment by dmlond** [comment]
our 'deploy' branch now has the basic rails application scaffolding for the metadata services, with rspec tests that do not test anything yet (we dont have any models, controllers, or endpoints to test yet).  It also has a circle.yml that specifies the correct ruby version.  The automated tests were set up by James to test all branches, so it automatically tested the deploy branch, which passes.

next step is to autodeploy to a heroku develop project

**Comment by jonturneratduke** [comment]
**Dependency on integration of authentication services running on Sal's (DHTS's) servers**

**Comment by jonturneratduke** [comment]
*Dependency on authentication services running on Sal's/DHTS's servers*

**Comment by dmlond** [comment]
currently, pushing changes to git develop branch automatically submits a CircleCI test.  If CircleCI test passes, CircleCI deploys the GitHub develop branch to the develop Heroku DDS application site.

**Comment by dmlond** [comment]
Dependency on issue #235

**Comment by dmlond** [comment]
Dependency on #235
