### ISSUE TITLE
Data has unique identifier

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service#4]
AAU, I want stored data to have a unique identifier so that I can find it later and have confidence the data is accurate/unchanged

**Comment by jonturneratduke** [comment]
The system will calculate a unique identifier for each data element and allow comparison of data to this identifier for verification

**Comment by erichhuang** [comment]
Recommend UUID version 4 (whichever uses SHA)

**Comment by dmlond** [comment]
UUID will refer to all provenance metadata after actual file is deleted from the system

**Comment by erichhuang** [comment]
One thing to consider too: if data are versioned and the initial UUID has a hash element, do we use the original URL/UUID as an "alias", or should we keep the URL and UUID separate? With Synapse, we have Synapse IDs, e.g. SYN1234556. Should we have something like DDS123456?
