### ISSUE TITLE
Add API endpoint to get project level metrics

### ISSUE THREAD

**Issue by mgardnerpsu** [Duke-Translational-Bioinformatics/duke-data-service#482]
Need endpoint to get total project collaborators, total project storage, etc...

**Comment by mgardnerpsu** [comment]
I will be adding an endpoint to projects that is liken to `/current_user/usage` - this will be `/projects/{id}/usage` and will include the following:
`member_count`
`file_count`
`storage_bytes`
@erichhuang @caseychoiniere Am I missing anything - I know Erich had requested visibility to some of these project level metrics on the portal side?

**Comment by caseychoiniere** [comment]
I might be wrong but I think he also wanted a way to get the total number of members across ALL projects.

**Comment by mgardnerpsu** [comment]
The endpoint has been added to the API spec and tagged as NOT_IMPLEMENTED_NEW
