### ISSUE TITLE
Method to get Portal URL for a project

### ISSUE THREAD

**Issue by dleehr** [Duke-Translational-Bioinformatics/duke-data-service#578]
We have a couple cases where we display a report or send an email with a link to a project. In both cases, we assemble the URL based on conventions we've seen in use:

https://github.com/Duke-GCB/DukeDSHandoverService/blob/28be78889e56832316aadd37a26d71cfcd7c008b/switchboard/dds_util.py#L28
https://github.com/Duke-GCB/DukeDSClient/blob/3095e7d31c6880a4a2aa4f6c9e2595e45c9a80ac/ddsc/core/upload.py#L81

This practice is fragile and will break when the API and Portal hosts are served from different domains.

Therefore, we request a service method for determining a project's portal URL. One suggestion would be to implement content negotiation on the `/projects/id` endpoint. So, if an agent requests 

```
GET /api/projects/abcd-1234-efgh-5678
```

With a header of `Accept: text/html`, the service would return HTTP 303, with the effective portal URL. If the agent requests it with `Accept: application/json`, the JSON content is returned as expected.

We suggest this as it leverages the standard.

**Comment by dmlond** [comment]
the best we could provide is an addition to /api/v1/app/status, e.g. portal_base_uri: https://dataservice.duke.edu/portal. Since the portal is a single page react application with its own router, we cannot reliably generate stable urls to portal pages. Anything we provided now would need to be updated when the portal changes from HashLocation to HistoryLocation, and would need to be managed in the future the portal changes its routing scheme.

**Comment by dleehr** [comment]
I understand it would need to be updated when the scheme changes - that's the whole point of the request. We're assembling project URLs based on a convention we inferred. We recognize that such a convention is scheduled to break, and it seems like a good opportunity to prevent that from happening in the future. Somewhere in the codebase, the recipe for a portal project URL exists, and I think it should be available to API users. Perhaps this issue belongs with the portal repository instead, but I'll leave that to you.

If this cannot be accommodated, what is the recommended practice? That we continue to reverse-engineer the URL scheme and fix it when it breaks? That we not use project URLs at all?

**Comment by dmlond** [comment]
At this point in the project, alpha phase 2, we do not have a recommended way for software_agent clients to generate urls to resources in the portal. We definitely need to address this, but it will need to be prioritized along with the other issues that we are addressing, and devote proper time to architect a reliable solution.
