### ISSUE TITLE
Build App Shell: Decision on Error Styles

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service#58]
Decide how to use styles to communicate errors to users

**Comment by jonturneratduke** [comment]
combination of visual style and consistency. finished when decisions are made and documented. (Casey) inline styles, bootstrap, ???

**Comment by caseychoiniere** [comment]
We will follow the Material Design guidelines for errors. Here is a page explaining the details
http://www.google.com/design/spec/patterns/errors.html#
