### ISSUE TITLE
Simplify SoftwareAgent/UserKey Setup

### ISSUE THREAD

**Issue by johnbradley** [Duke-Translational-Bioinformatics/duke-data-service#622]
Right now for the DukeDSClient there is a rather large set of steps required to setup your software agent and user keys:
https://github.com/Duke-GCB/DukeDSClient/blob/master/docs/GettingAgentAndUserKeys.md
The down side of this is every new user ends up with a unique 'DukeDSClient' software agent key.

A simpler workflow could be:
1) click Software Agents
2) click a software agent that allows users to download it's key
3) click "Download Key File"
This key file would contain the software agent key and the users key.

Some software agents would want to prevent this behavior so we would probably need a switch.

**Comment by johnbradley** [comment]
Just for some context, we mentioned this yesterday in a meeting with @jonturneratduke and @mgardnerpsu.

**Comment by dmlond** [comment]
This is something that has been slated for development from the very beginning of the project. I do not see any technical or security roadblocks to developing it in the way you describe. It will need to be prioritized with the rest of the development roadmap features.  As a workaround for now, you could store the client agent key inside the source code for the client. This would remove the 'get agent key' step from the list. Even with this newly described system, there is no way to prevent users from 'masquerading' their own code as your client, so I am not sure it would be a huge security issue to provide a single agent key to all of your users with the code.

**Comment by caseychoiniere** [comment]
I think this is a nice flow too. We discussed this when building the UI for software agents. For one reason or another we decided not to implement it this way, I'm going to try to find the conversation on that topic.

**Comment by caseychoiniere** [comment]
I made some changes to software agents. Now you can just create an agent and click on the credentials button. It will create a user key for you if you don't have one and then display the `agent_key`, `user_key` and `api_token` in JSON format. You can then use the copy to clipboard button to copy this. 
![screen shot 2016-05-10 at 5 36 32 pm](https://cloud.githubusercontent.com/assets/10411174/15166669/08538158-16d6-11e6-9768-32eb0eac51ce.png)

**Comment by johnbradley** [comment]
Thanks. This will really simplify setup for DukeDSClient users.

**Comment by caseychoiniere** [comment]
I think this can be closed.
