### ISSUE TITLE
API allows users to add another user with system_admin privileges

### ISSUE THREAD

**Issue by johnbradley** [Duke-Translational-Bioinformatics/duke-data-service#665]
For this endpoint: 
`PUT /api/v1/projects/{project_id}/permissions/{user_id}` - Grant project level permissions to a user
You can specify system_admin and the api allows it and updates the project with those permissions.

Not sure if this is a security loophole.

The UI for the portal shows Dan as an admin after doing this:
<img width="413" alt="screen shot 2016-07-13 at 2 02 32 pm" src="https://cloud.githubusercontent.com/assets/1024463/16814139/7d4a75f8-4902-11e6-98f9-c7dbdc7adfe7.png">

The reason I am asking is I was changing ddsclient to list the available auth roles `GET /api/v1/auth_roles` and this included system_admin.

**Comment by dmlond** [comment]
are you using the dev, uatest, or prod api instance?

**Comment by dmlond** [comment]
This is not a security threat. Your user is not a system admin in the system.  It is a bug, as it should not allow you to create a project role with an AuthRole that does not have the project context.  Your client should either call for auth_roles with the context: 'project', or filter out the returned auth_roles that are not context: 'project'.

**Comment by johnbradley** [comment]
This was on the production api.
