### ISSUE TITLE
Feature Request: Single API endpoint to download project directory tree

### ISSUE THREAD

**Issue by johnbradley** [Duke-Translational-Bioinformatics/duke-data-service#671]
Right now to upload a pre-existing project requires making many separate API requests.
`/api/v1/projects/{id}/children` - to get the project's folders/files
`/api/v1/folders/{id}/children` - to get the folder's subfolders/files 
`/api/v1/files/{id}` - to get the hash of the file
So for a directory with 1000 files we make a large number of API requests.
Each of these takes about 0.25 seconds to complete.
In some cases we can spend more time requesting file hashes than actually uploading the changes.

Would it be possible to have an endpoint that give us the directory tree in one request?
That way we would be able to get back all folder names, file names and file hashes in one request.

Thanks.

**Comment by jonturneratduke** [comment]
Makes sense. Recently we saw a project with 20,000 files and launch times of 40 minutes to 1 hour to collect all this info and restart the upload. This proposed approach would chop that to a small fraction. The returned JSON payload could be sizable though.

DDS Team: We'll likely need this same functionality for our own sync host or bulk-upload tool or whatever.

**Comment by dmann** [comment]
If the children endpoints are passed an empty name_contains parameter, all of the parent object's descendants are returned. For example, `/api/v1/projects/{id}/children?name_contains=` would return all the folders and files for the given project id. I recently updated folders such that `/api/v1/folders/{id}/children?name_contains=` is a bit more snappy, but you probably won't need to call that if you query at the project level.

**Comment by johnbradley** [comment]
The API explorer doesn't mention this for that parameter, but [ddsedge.apiary](http://docs.ddsedge.apiary.io/#reference/search-children/search-project-children/search-project-children) details this behavior:
```
Searches the immediate children of the project unless the name_contains parameter 
is specified; when specified, the name_contains parameter invokes a recursive search
of the project hierarchy.
```
Thanks for the help.
