### ISSUE TITLE
503 when deleting project containing many folders

### ISSUE THREAD

**Issue by johnbradley** [Duke-Translational-Bioinformatics/duke-data-service#722]
I've started getting a 503 back when deleting a project with ~1000 folders.
If I wait a while the project eventually disappears.

To reproduce:
Go to https://api.dataservice.duke.edu/apiexplorer#!/projects/DELETE_api_version_projects_id_format

Enter this project id `28349202-354b-4ad9-9b80-875b990ef5b3`.

The above will only work once since it eventually deletes the project.

From the portal:
It takes you back the the main screen and you still see the project.
If you refresh the page enough it will disappear.

**Comment by johnbradley** [comment]
Looks like this isn't just isolated to deleting projects.
I've seen error 503 on the following endpoints:
```
/projects/e0b0f3be-fc30-4080-b491-639594b8dc40/uploads
/files/
/uploads/535d9e0a-dbb5-48c3-92b1-039e02c6282e/complete
/software_agents/api_token
```

**Comment by dmlond** [comment]
What specific calls are you making on these endpoints?  I am able to use the swagger frontend to login and get /projects.

**Comment by johnbradley** [comment]
For deleting the project I was sending DELETE to /api/v1/projects/28349202-354b-4ad9-9b80-875b990ef5b3.  This one happens every time with that particular project.

They were working earlier today but for the last few hours different methods fail randomly.
This one is just a plain PUT: /uploads/535d9e0a-dbb5-48c3-92b1-039e02c6282e/complete

The two examples above any form data that must be sent with them.

Are you able to see anything in error logs on the server?

Thanks.
