### ISSUE TITLE
Agent property in user response payload

### ISSUE THREAD

**Issue by mgardnerpsu** [Duke-Translational-Bioinformatics/duke-data-service#741]
Not sure what "agent" property represents in the user payload? - seems like it would be contained within "created_by", "last_updated_by", or "deleted_by" if relevant from audit perspective?

{
  "id": "742569cf-ca14-4676-8c71-2084cd594c88",
  "username": "londo003",
  "full_name": "Darin London",
  "first_name": "Darin",
  "last_name": "London",
  "email": "darin.london@duke.edu",
  "auth_provider": {
    "uid": "londo003",
    "source": "Duke Authentication Service"
  },
  "last_login_on": "2016-09-19T18:47:15.149Z",
  "audit": {
    "created_on": "2016-09-19T18:47:15.348Z",
    "created_by": {
      "id": "742569cf-ca14-4676-8c71-2084cd594c88",
      "username": "londo003",
      "full_name": "Darin London"
    },
    "last_updated_on": null,
    "last_updated_by": null,
    "deleted_on": null,
    "deleted_by": null
  },
  "agent": null
}

**Comment by dmlond** [comment]
This will be null for any call to show another user, or when /api/v1/current_user is called in the context of a browser login. If the user uses a software_agent (when they call /api/v1/software_agents/api_token, the JWT stores both their userid, and their software_agent id) to call /api/v1/current_user, information about the software_agent they are using is returned in this field.

**Comment by mgardnerpsu** [comment]
Explanation above clarified that this was not a bug, but intended behavior
