### ISSUE TITLE
`DELETE /api/v1/templates/{id}`

### ISSUE THREAD

**Issue by caseychoiniere** [Duke-Translational-Bioinformatics/duke-data-service#760]
`DELETE /api/v1/templates/{id}` should not allow a template to be deleted if it has been associated to one or more DDS objects. But I'm able to create templates, associate them with files and then delete them.

**Comment by dmann** [comment]
Good catch. This will be an issue for properties as well. I've created an issue on our Jira board and will take care of this either today or early next week.
