### ISSUE TITLE
POST/search/provenance/was_generated_by - No validation error thrown

### ISSUE THREAD

**Issue by caseychoiniere** [Duke-Translational-Bioinformatics/duke-data-service#770]
The docs state: All of the provided file versions must exist or a validation error is returned.

But I can provide any random id and no error is thrown.

For example I can provide this request body and it still works without a validation error

``` javascript
body: JSON.stringify({
            file_versions: [{
                id: "this is a fake id"
            }]
        })
```

**Comment by mgardnerpsu** [comment]
Updated docs to reflect implementation... if a provided file version does not exist, then no provenance nodes/relations are returned (a validation exception is not raised)
