### ISSUE TITLE
Provenance: Relations business rules conflicts

### ISSUE THREAD

**Issue by caseychoiniere** [Duke-Translational-Bioinformatics/duke-data-service#776]
Docs state that: 

**An entity (i.e. file_version) can be generated by one and only one activity (i.e. dds-activity).
An entity (i.e. file_version) cannot be used and generated by the same activity (i.e. dds-activity).**

No error is thrown and the API allows files_versions to have many wasGeneratedBy relations and can also be used and generated by the same activity.

This happens with 
`POST/relations/was_generated_by` 

`POST/relations/used` also does not throw an error when an entity (i.e. file_version) is used and generated by the same activity (i.e. dds-activity).

**Comment by Donmurry** [comment]
Solved with JIRA issue [DDS-689](https://jira.oit.duke.edu/browse/DDS-689?jql=project%3Ddds%20and%20issuetype%3Dbug%20and%20createddate%3E%202016-10-01%20and%20status%20%3D%20resolved)
