### ISSUE TITLE
uploads/{id}/chunks returns expired url if called twice 5 min apart

### ISSUE THREAD

**Issue by johnbradley** [Duke-Translational-Bioinformatics/duke-data-service#809]
Recently a bug was fixed where you couldn't upload the same chunk twice.
Now you can but if you wait 5 minutes the url errors with a 401 back from swift.

To reproduce go here:
https://api.dataservice.duke.edu/apiexplorer#!/uploads/putApiV1UploadsIdChunks
Fill out all the fields and click 'try it out'.
Record the value for `temp_url_expires` in the url returned.
Wait 5 minutes.
click 'try it out'.
You should see the same value for `temp_url_expires`.
If you try to use this url you will get unauthorized 401 back from swift.

You can convert from the number after temp_url_expires like so:
```
date -r <number>
```

@jonturneratduke this came up because I am trying to allow DukeDSClient to support resumable uploads.

Thanks.

**Comment by dmlond** [comment]
our swift urls are designed to expire in 5 minutes. We can increase the time, but we do cannot make them too long, or they can become a security hazard.  I would think there is a way to respond to a 401 from swift with a request for a new (fresh) chunk url for that chunk from the same endpoint.

**Comment by johnbradley** [comment]
When trying to create new (fresh) chunk url it returns a stale upload url the second time.

Workflow:
At 12:30 I send a PUT to /api/v1/uploads/{id}/chunks number=1 to create a url.
The url returned expires at 12:35.
...pretend I loose internet connection for 20 min...
At 12:50 I send a PUT to /api/v1/uploads/{id}/chunks number=1 to create a fresh url.
The url returned expires at 12:35? I expected it to expire at 12:55.

**Comment by dmlond** [comment]
ahh, ok. I will take a look.

**Comment by dmlond** [comment]
deployed fix to development system. Please try it and let me know if it is still a problem.

**Comment by johnbradley** [comment]
Testing against `https://apidev.dataservice.duke.edu/api/v1` this works for me now.
I tested two scenarios:
1. creating a chunk url, waiting 5 minutes, recreating the chunk url, and finishing the upload
2. creating a chunk url, upload chunk, wait 5 minutes, recreating the chunk url, reupload chunk and finishing the upload.

**Comment by dmlond** [comment]
great. closing this bug
