### ISSUE TITLE
Fix user info for omicscore username

### ISSUE THREAD

**Issue by johnbradley** [Duke-Translational-Bioinformatics/duke-data-service#810]
The `full_name` and `email` fields are null for user omicscore.
https://api.dataservice.duke.edu/api/v1/users
Could you fill in these values
```
full_name = 'Genomic Analysis'
first_name: 'Genomic'
last_name': 'Analysis'
email = 'GenomicAnalysis@duke.edu'
```
Looks like the id in production for this user is `f547b256-ce9c-4aed-8b7f-0aeaae4de14d`.

This came out of a meeting with @jonturneratduke  today.

Thanks.

**Comment by dmlond** [comment]
done
