### ISSUE TITLE
POST /api/v1/meta/{object_kind}/{object_id}/{template_id} - Incorrect error response

### ISSUE THREAD

**Issue by caseychoiniere** [Duke-Translational-Bioinformatics/duke-data-service#811]
When creating a metadata object with `POST /api/v1/meta/{object_kind}/{object_id}/{template_id}` it returns a 500 error response when it should return a 400 response. It does this when trying to add a value of the incorrect datatype to a template key.

Steps to replicate:
1.) Create a template
2.) Create a property for that template and set the datatype to "integer"
3.) Create a metadata object using `POST /api/v1/meta/{object_kind}/{object_id}/{template_id}` and set the value of the property to a string. 

Results: 
DDS will return an HTTP error response of 500 rather than a 400 validation error.

**Comment by dmlond** [comment]
Is this different than Issue #765

**Comment by caseychoiniere** [comment]
No, sorry about that. Just came across this again today while working. Didn't realize I had already logged it a few  weeks back.
