### ISSUE TITLE
Align kind values for relations with API spec

### ISSUE THREAD

**Issue by mgardnerpsu** [Duke-Translational-Bioinformatics/duke-data-service#815]
In reviewing DREDD output it looks like the `kind` values for relations do not align with API spec.  For example: `dds-derived_from_file_version_prov_relation` vs. `dds-relation-was-derived-from`.  All of the kinds should follow convention `dds-relation-<W3C name>`.  See docs...

**Comment by Donmurry** [comment]
Addressed with JIRA issue [DDS-731](https://jira.oit.duke.edu/browse/DDS-731)
