### ISSUE TITLE
Search objects returns 400 bad request

### ISSUE THREAD

**Issue by mgardnerpsu** [Duke-Translational-Bioinformatics/duke-data-service#816]
When executing sample query from API spec - always GET 400 bad data response... spec may not align with current implementation - need to investigate.  Error message should be more informative.

**Comment by dmlond** [comment]
this is a problem with the apidocs example :).  The apidocs example is
```
```
but it should be
```
{
    "included_kinds": ["dds-file"],
    "search_query": {
        "query": {
            "match" : {
                "_all" : "SMRT sequencing"
             }
        }
    }
}
```
note the missing closing curlybrace after the "_all" : "SMRT sequencing" section (that causes the 400 error), and 'include_kinds' vs 'included_kinds' (causes another error after fixing the missing curlybrace)

**Comment by caseychoiniere** [comment]
Thanks Darin!

**Comment by mgardnerpsu** [comment]
The docs have been updated per DL feedback.  Thanks Darin...
