### ISSUE TITLE
Can't update object metadata instance for some files

### ISSUE THREAD

**Issue by caseychoiniere** [Duke-Translational-Bioinformatics/duke-data-service#826]
For some reason occasionally I'm not able to update an object metadata instance for some files. It happens sporadically and not very often. 

Here is an example file and template that for some reason fails anytime you try to update it. It fails with a 400 error and this message

```javascript
{
  "error": "400",
  "reason": "validation failed",
  "suggestion": "Fix the following invalid fields and resubmit",
  "errors": [
    {
      "field": "template",
      "message": "has already been taken"
    }
  ]
}
```

Check the screenshot for the info on the file, template and a property to use to reproduce this.
<img width="744" alt="screen shot 2016-11-18 at 12 13 33 pm" src="https://cloud.githubusercontent.com/assets/10411174/20441322/9d5fdab8-ad89-11e6-897f-3891a24fa752.png">
<img width="688" alt="screen shot 2016-11-18 at 12 14 29 pm" src="https://cloud.githubusercontent.com/assets/10411174/20441331/a6303610-ad89-11e6-80e4-3474ff9175d2.png">

@dmann I granted you access to this file so you could reproduce this. It fails both in the portal and in the API explorer.

**Comment by caseychoiniere** [comment]
This is a transient bug. I've come across it about 4 times and each time is very random. It seems to happen after metadata properties have been edited multiple times for the same metadata object instance.

**Comment by dmann** [comment]
I searched through the logs and there were two MetaTemplate entries for the above object_id and template_id. It looks like we're dealing with a race condition when a Metadata instance is being created, similar to what we were dealing with when duplicate users were showing up in the database. The difference being that the duplicate users were being created under a GET request (which did some sort of pre-flight call), and the Create MetaTemplate endpoint is a POST. 

So, I wouldn't have expected a POST endpoint to be slammed like this. But, we can go ahead and put a transaction lock on the table to prevent any more of these from slipping through.
