### ISSUE TITLE
Partial match search on meta properties

### ISSUE THREAD

**Issue by caseychoiniere** [Duke-Translational-Bioinformatics/duke-data-service#849]
Can't get a partial match search to work on meta properties. Not sure if this is a problem with my queries or ??? 

Here is an example query that works for partial matches on names and tags but not meta properties.

```javascript
{
       "include_kinds": ['dds-file', 'dds-folder'],
       "search_query": {
           "query": {
               "multi_match" : {
                   "query":      "x8x",
                   "type":       "phrase_prefix",
                   "fields":     [ "tags.*", "meta.*", "name" ]
               }
           }
       }
}
```
I can get an exact match to work by using `match_all` like so

```javascript
{
  "query": {
    "match" : {
      "_all": "x8x9x0"
    }
  }
}
```

**Comment by dmann** [comment]
@caseychoiniere Are you still having problems with this type of query?

**Comment by caseychoiniere** [comment]
Nope, looks like this is addressed now. Thanks!
