### ISSUE TITLE
Metadata Templates name_contains parameter is scoped to template creator

### ISSUE THREAD

**Issue by caseychoiniere** [Duke-Translational-Bioinformatics/duke-data-service#860]
Metadata Templates name_contains parameter is scoped to template creator? It doesn't allow for searching through templates that were created by other users. If I search for a template created by someone else I always get an empty array as the result.

**Comment by dmann** [comment]
Could you provide an example of what your name_contains parameter is set to and your expected results? We're not currently scoping the results, but (the way endpoint is currently written) I could see the potential for case-sensitivity issues.

**Comment by caseychoiniere** [comment]
You know what. Scratch this, I know what's happening. The display labels people are using are not in line with the actual template name they use. Thus I do a search for a label expecting to get relevant results and nothing is returned. This is pretty confusing for the user... Not a bug though. It's just the API design.
