### ISSUE TITLE
500 Error on file upload - Production

### ISSUE THREAD

**Issue by caseychoiniere** [Duke-Translational-Bioinformatics/duke-data-service#875]
I'm copying this over from a Usersnap feedback. This is both a Portal and a DDS issue. It doesn't look like the portal handled the 500 error at some point during the upload process. But also, there was a server error at some point too. Without more details not sure how to investigate this. https://github.com/Duke-Translational-Bioinformatics/duke-data-service-portal/issues/553

**Comment by dmlond** [comment]
this is happening because we experiencing problems with the elasticsearch index creation:
```
Jan 12 11:42:24 dukeds app/web.1: [429] {"error":"Concurrent request limit exceeded. Please consider batching your requests, or contact support@bonsai.io for help.","status":429}
```
we are working on developing a background job system to ensure that all files are indexed, with retry logic to handle this kind of transient error.
