### ISSUE TITLE
Uploading a 29GB file fails at /uploads/.../complete step

### ISSUE THREAD

**Issue by johnbradley** [Duke-Translational-Bioinformatics/duke-data-service#881]
This is when using ddsclient.

Reproducing on OSX the following:
```
mkfile -n 29G bigboy.img
ddsclient upload -p bigboy bigboy.img
```

You then see this error:
```
Error 503 on /uploads/df9eba51-f971-4558-b147-cde5c9a5934e/complete Reason: Suggestion:
```

What's odd is a 30GB file I tried worked.

Issue on DukeDSClient: https://github.com/Duke-GCB/DukeDSClient/issues/101

**Comment by johnbradley** [comment]
FYI: @jonturneratduke

**Comment by johnbradley** [comment]
This particular project allso fails with a 503 when you try to search files.
From the web portal you can see the 503 in the javascript console.
It can also be seen from the API Explorer:
https://api.dataservice.duke.edu/apiexplorer#!/projects/getApiV1ProjectsIdChildren
__name_contains:__ a
__id:__ d8ac1d2e-b96a-4dd1-a433-60a8db22ee26
click [Try it Out]
returns 503 and a webpage containing an iframe referencing
`www.herokucdn.com/error-pages/application-error.html`
I can reproduce this on demand.

**Comment by dmann** [comment]
@johnbradley This is a big project and that request is attempting to return all of its child files and folders at once. Unfortunately, it's taking longer than 30 seconds to complete the call, which is what Heroku has set as their request timeout. To make matters worse, the matter in which Heroku is killing the request is causing a memory leak, which eventually leads to swapping, which slows everything down and causes more request timeouts.

I'm going to work on the memory leak today, but that will not solve the request timing out. We implemented pagination to address this very issue, though it has not been released to production yet. I suggest that you replicate this project to the uatest instance of our api and do your testing there.

**Comment by johnbradley** [comment]
Thanks @dmann. I have forthcoming DukeDSClient changes that will make us of paging so that may resolve the 503 error. I will try it out against a project with many files in uatest.
However there is still the initial 503 that occurred when trying to complete the uploaded file.
Do you think there are changes in uatest that might help with this as well?

**Comment by dmann** [comment]
It's hard to say what happened with those calls to complete the upload. The logs aren't super helpful. New Relic APM is indicating that the PUT call to swift took 20 seconds for that call. I don't have a reason as to why though. Maybe try your 29G file test on uatest and see if you get the same result.

**Comment by johnbradley** [comment]
I was able to upload the 29G file in uatest two times without any error.
I was also able to upload it in production today.
