### ISSUE TITLE
Remove Portal folder and assets from DDS repo

### ISSUE THREAD

**Issue by caseychoiniere** [Duke-Translational-Bioinformatics/duke-data-service#882]
I just noticed that the old portal folder is still in the DDS repo. Now that we don't use this it can be removed.

https://github.com/Duke-Translational-Bioinformatics/duke-data-service/tree/develop/portal

**Comment by dmlond** [comment]
yeah, it's been on my list, but hasn't been a priority. Do you think it is causing any confusion, or security issues? If so, I can prioritize it sooner.

**Comment by caseychoiniere** [comment]
Nope,  I really don't think it's a priority. I just noticed it when I was trying to find info/relevant code on the OIT Oauth that you set up the Swagger UI with.
