### ISSUE TITLE
Provenance - search/provenance/origin Random 404 Errors 

### ISSUE THREAD

**Issue by caseychoiniere** [Duke-Translational-Bioinformatics/duke-data-service#888]
`POST/search/provenance`

For some reason a file on dev always throws a 404 when I try to retrieve provenance for it. This happens when I check it in API explorer as well.

I've tried other files and they work just fine. Seems to be isolated to this file for some reason.

**File version ID** used for retrieving provenance graph is `644b1e5f-0368-456d-948e-0060015803b9`

**Error message in response** is `{"error":"404","reason":"object_kind dds-used_prov_relation Not Supported","suggestion":"Please supply a supported object_kind"}`

**File ID** is `12138ab1-1cba-45f7-bc75-4692f2ccc3e5`

@dmlond  I granted you access to this project so you can mess with this file if you need to. 

Also, I tried performing other actions on the file like editing the name etc. and they all work fine.

**Comment by caseychoiniere** [comment]
One more piece of info: I was able to add the file to another proveance graph and add a relation to it but it still throws a 404 when doing a `POST/search/provenance` for it.

**Comment by dmlond** [comment]
dev or uatest?

**Comment by dmlond** [comment]
looks like the development graphstory instance is down.

**Comment by dmlond** [comment]
now I get a Java heap space error for the Cypher query that runs for this particular request :(

**Comment by dmlond** [comment]
try this again. I fixed the graph mappings for kind to match with what I pushed out yesterday :)

**Comment by caseychoiniere** [comment]
That fixed it!
