### ISSUE TITLE
uatest: Upload 100 files 500 error on post to /files/ (randomly)

### ISSUE THREAD

**Issue by johnbradley** [Duke-Translational-Bioinformatics/duke-data-service#890]
When uploading 100 sample files to uatest using ddsclient I receive back a 500 error.
Steps(after setting up ddsclient for uatest):
```
mkdir data && for i in $(seq 100); do date >> data/$i.txt; done
ddsclient upload -p 100_files data/
```
You may need to run this a few times to see it fail(with different project names obviously).

I have been deleting the projects as part of this testing which always results in a 500 error. 

This might be related to part of #881 since this is a project containing many files.

Is there anything in the logs for the 500 errors?

**Comment by johnbradley** [comment]
fyi: @jonturneratduke

**Comment by johnbradley** [comment]
I found the POST to `/files/` will succeed if I tried again later. Perhaps this is another case related to server load.

**Comment by jonturneratduke** [comment]
Do you have a time range this happened so we can look at the logs? I see a big spike of activity around 10:30am, 11:40-12:20, and again at 1:10pm.

Also, when you say it worked later, how much later? Is that seconds, minutes, hours?
Agreed it sounds like a server load issue.

**Comment by johnbradley** [comment]
11:40-12:20 sounds correct.
I tried it again this morning on uatest.
I had one 500 error at Jan 26 08:25:02 EST 2017 on the POST to `/files/` on uatest. 
The next two times it worked.
Thanks.
