### ISSUE TITLE
POST /files/ endpoint allows re-using upload

### ISSUE THREAD

**Issue by johnbradley** [Duke-Translational-Bioinformatics/duke-data-service#892]
In looking to support resumable uploads (https://github.com/Duke-GCB/DukeDSClient/issues/86) I found that I can re-use the same upload to duplicate a file.

Steps:
1) Create project with a file using web portal
2) Use api explorer to find the parent kind, parent id and upload id:
`https://apiuatest.dataservice.duke.edu/apiexplorer#!/files/getApiV1FilesId`
3) Fill that data in here and click "Try it out" a few times:
`https://apiuatest.dataservice.duke.edu/apiexplorer#!/files/postApiV1Files`
4) Look at your project again in the web portal and you will see that it is duplicated.

Ideally I would like an error back that would let me know that this file is already created.
fyi: @jonturneratduke

**Comment by dmlond** [comment]
This is a feature, not a bug.  Each File represents a single entity, with its own life-history, versioning, etc. It is essentially a 'fork' of the same upload. As an example, consider the case where the same empty excel spreadsheet with survey headers is uploaded as version 1 of 5 separate Files, e.g. the same survey being performed for 5 different experiments. Each File would evolve over time to include new information attached to each experiment. Each version would have a new upload of the excel spreadsheet with new data, but one could follow the Prov chain back to the original Files and file_versions, and verify that they all started from the same upload with the same md5.

**Comment by johnbradley** [comment]
OK. Thanks.
