### ISSUE TITLE
file upload: fingerprinting

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service#91]
(if not supported by file system) MD5? SHA1?

**Comment by erichhuang** [comment]
SHA1+

**Comment by jonturneratduke** [comment]
calc checksum clientside. Have resolver API also calc checksum and compare after upload. if !=, throw error

**Comment by erichhuang** [comment]
May be prudent at some point to do some performance testing on big files. How long does it take to compute a SHA-X on a 1TB file? And on a typical researcher's hardware?
