### ISSUE TITLE
GET /api/v1/auth_providers/{id}/affiliates - Errors with less then 5 chars in search params

### ISSUE THREAD

**Issue by caseychoiniere** [Duke-Translational-Bioinformatics/duke-data-service#957]
When I make a request to `GET /api/v1/auth_providers/{id}/affiliates` in the api explorer using 3 characters from  my last name `cho` I get this random error
```javascript
{
  "error": "404",
  "reason": "undefined method `reject' for nil:NilClass",
  "suggestion": "Please supply a supported object_kind"
}
```
When I supply 4 characters from my last name `choi` I get this random error
```javascript
{
  "error": "404",
  "reason": "undefined method `mail' for #<Net::LDAP::Entry:0x007f6baaed69b8>",
  "suggestion": "Please supply a supported object_kind"
}
```
and when I supply at least 5 characters  `choin` it works as expected.  But when I supply my full first name which is 5 characters, I also get an error.  In fact I get an error until I supply at least `casey ch`

**Comment by dmlond** [comment]
This should work now.
