### ISSUE TITLE
Tagging service not working

### ISSUE THREAD

**Issue by caseychoiniere** [Duke-Translational-Bioinformatics/duke-data-service#966]
Tagging service seems to be messed up since background jobs were deployed. DELETE and POST/append definitely don't work. Not sure about the others, don't have time to test them all. For reference, in api explorer this is the error
```{
  "error": "404",
  "reason": "undefined method `transactionable' for nil:NilClass",
  "suggestion": "Please supply a supported object_kind"
}```

**Comment by dmann** [comment]
@caseychoiniere I think this should be fixed in develop now. Give it a whirl and let us know if anything's amiss.

**Comment by caseychoiniere** [comment]
@dmann Yep, looks good.
