### ISSUE TITLE
Unable to create folders without 500 error in dev and uatest

### ISSUE THREAD

**Issue by johnbradley** [Duke-Translational-Bioinformatics/duke-data-service#981]
You can reproduce this in the web UI by creating a new project and trying to create a top level folder.
It does create the folder. If you click refresh in the browser the folder shows up.
It can also be reproduced with ddsclient or the apiexplorer.

FYI: @jonturneratduke

**Comment by caseychoiniere** [comment]
Maybe related to this behavior I posted on Slack the other day? 
https://dukefrds.slack.com/archives/C0AN58F0A/p1491934658568860

**Comment by johnbradley** [comment]
I am no longer seeing this issue. Based on Slack it looks like @dmlond fixed this by rebuilding the elasticsearch file/folder indices.
