### ISSUE TITLE
file upload: obtain DHTS host for resolver

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service#99]
Obtain DHTS server to host Resolver. (@Sal / @Kris Hamilton, DHTS Engineering, Dependency)

**Comment by jonturneratduke** [comment]
2 servers for dev, 2 for test.

**Comment by jonturneratduke** [comment]
Matt will send email
need servers with isolon mounted (we will specify mountpoints) (matt to talk to D&D)
need test and dev mountpoints.

sudo access for darrin, darin, jason, chet

**Comment by jonturneratduke** [comment]
very basic needs for server:
	sudo
	mount shares
	ability to SSH in
that's it.

**Comment by jonturneratduke** [comment]
update from Sal Monday 5:30pm : 2 servers are being built by DHTS now, should be available "in a day or two"

**Comment by jonturneratduke** [comment]
Thursday 5pm followup -- still waiting.

**Comment by jonturneratduke** [comment]
From: Alex Martin
Sent: Thursday, July 16, 2015 8:10 PM
To: Joel Davis; Sal Munguia; Jonathan Turner
Subject: RE: FRDS Isolon storage
 
Joel, excellent update.

The 2 VMs that were waiting for Networker registration has been closed and now are in the QA queue.
 
The other 2, I have sent out for building this evening.
 
Thank you!
 
**************************************
Alex Martin
(o) 919.684.7636
Hosting Team Lead, Service Delivery
Virtualization & Citrix Infrastructure
**************************************
 
From: Joel Davis 
Sent: Thursday, July 16, 2015 6:15 PM
To: Sal Munguia <sal.munguia@dm.duke.edu>; Jonathan Turner <jonathan.turner@dm.duke.edu>
Cc: Alex Martin <alex.martin@dm.duke.edu>
Subject: RE: FRDS Isolon storage
 
These are all waiting on other groups. RITM0760430 was waiting on us though, but I just kicked that over to the backup team (just got the IP for the backup interface today). Most of the others are waiting for the VMWare team to finish up. I don’t think these are going to involve the OS becoming unavailable so I think the VM’s themselves are probably alright to start your work on with the idea that there are still some post-install tasks going on in the background from DHTS.
 
Regards,
 
Joel Davis
Systems Analyst (Unix/Linux)
Desk: 919-613-6431  Mobile: 919-338-6218
Normal Office Hours: 8:30 AM until 5:30 PM (11:30 AM lunch)
 
From: Sal Munguia 
Sent: Thursday, July 16, 2015 6:08 PM
To: Jonathan Turner; Joel Davis
Subject: Re: FRDS Isolon storage
 
 
Joel, 
 
Can you provide us with an update for these servers? 
 
|Ticket#|Notes|Date|Status|
|RITM0760427|Server Request Test 1|7-9-15|IP|
|RITM0760428|Server Request Test 2|7-9-15|IP|
|RITM0760429|Server Request  Dev 1|7-9-15|IP|
|RITM0760430|Server Request Dev 2|7-9-15|IP|

**Comment by jonturneratduke** [comment]
Servers are now available. Need to check access for DM/DL, Mounts & SSH access

**Comment by jonturneratduke** [comment]
If we use ECS /openstack, we don tneed isilon mount. Can we close this out?

**Comment by mgardnerpsu** [comment]
The dev/test servers have been provisioned with 28GB of mounted storage (non-isilon).  The 1TB of isilon storage (shared between dev and test) still pending.
